package utils;

import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.MimeMessage;
import javax.activation.DataHandler;
import javax.activation.DataSource;

public class EmailService {

    private static final String FROM = "lhmsswp391@gmail.com";
    private static final String PASSWORD = "swpkteujuqnauatb";

    public static void sendMailToRegister(String emailTo, String user_token) {
        String link = "\"" + "http://localhost:9999/ManageLodgingHouse/LoginServlet?service=verifyAccount&user_token=" + user_token + "\"";
        String content = "<!DOCTYPE html>\n"
                + "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\"\n"
                + "    xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
                + "\n"
                + "<head>\n"
                + "    <meta charset=\"utf-8\"> <!-- utf-8 works for most cases -->\n"
                + "    <meta name=\"viewport\" content=\"width=device-width\"> <!-- Forcing initial-scale shouldn't be necessary -->\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> <!-- Use the latest (edge) version of IE rendering engine -->\n"
                + "    <meta name=\"x-apple-disable-message-reformatting\"> <!-- Disable auto-scale in iOS 10 Mail entirely -->\n"
                + "    <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->\n"
                + "\n"
                + "    <link href=\"https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700\" rel=\"stylesheet\">\n"
                + "\n"
                + "    <!-- CSS Reset : BEGIN -->\n"
                + "    <style>\n"
                + "        /* What it does: Remove spaces around the email design added by some email clients. */\n"
                + "        /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */\n"
                + "        html,\n"
                + "        body {\n"
                + "            margin: 0 auto !important;\n"
                + "            padding: 0 !important;\n"
                + "            height: 100% !important;\n"
                + "            width: 100% !important;\n"
                + "            background: #f1f1f1;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Stops email clients resizing small text. */\n"
                + "        * {\n"
                + "            -ms-text-size-adjust: 100%;\n"
                + "            -webkit-text-size-adjust: 100%;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Centers email on Android 4.4 */\n"
                + "        div[style*=\"margin: 16px 0\"] {\n"
                + "            margin: 0 !important;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Stops Outlook from adding extra spacing to tables. */\n"
                + "        table,\n"
                + "        td {\n"
                + "            mso-table-lspace: 0pt !important;\n"
                + "            mso-table-rspace: 0pt !important;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Fixes webkit padding issue. */\n"
                + "        table {\n"
                + "            border-spacing: 0 !important;\n"
                + "            border-collapse: collapse !important;\n"
                + "            table-layout: fixed !important;\n"
                + "            margin: 0 auto !important;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Uses a better rendering method when resizing images in IE. */\n"
                + "        img {\n"
                + "            -ms-interpolation-mode: bicubic;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Prevents Windows 10 Mail from underlining links despite inline CSS. Styles for underlined links should be inline. */\n"
                + "        a {\n"
                + "            text-decoration: none;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: A work-around for email clients meddling in triggered links. */\n"
                + "        *[x-apple-data-detectors],\n"
                + "        /* iOS */\n"
                + "        .unstyle-auto-detected-links *,\n"
                + "        .aBn {\n"
                + "            border-bottom: 0 !important;\n"
                + "            cursor: default !important;\n"
                + "            color: inherit !important;\n"
                + "            text-decoration: none !important;\n"
                + "            font-size: inherit !important;\n"
                + "            font-family: inherit !important;\n"
                + "            font-weight: inherit !important;\n"
                + "            line-height: inherit !important;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Prevents Gmail from displaying a download button on large, non-linked images. */\n"
                + "        .a6S {\n"
                + "            display: none !important;\n"
                + "            opacity: 0.01 !important;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Prevents Gmail from changing the text color in conversation threads. */\n"
                + "        .im {\n"
                + "            color: inherit !important;\n"
                + "        }\n"
                + "\n"
                + "        /* If the above doesn't work, add a .g-img class to any image in question. */\n"
                + "        img.g-img+div {\n"
                + "            display: none !important;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Removes right gutter in Gmail iOS app: https://github.com/TedGoas/Cerberus/issues/89  */\n"
                + "        /* Create one of these media queries for each additional viewport size you'd like to fix */\n"
                + "\n"
                + "        /* iPhone 4, 4S, 5, 5S, 5C, and 5SE */\n"
                + "        @media only screen and (min-device-width: 320px) and (max-device-width: 374px) {\n"
                + "            u~div .email-container {\n"
                + "                min-width: 320px !important;\n"
                + "            }\n"
                + "        }\n"
                + "\n"
                + "        /* iPhone 6, 6S, 7, 8, and X */\n"
                + "        @media only screen and (min-device-width: 375px) and (max-device-width: 413px) {\n"
                + "            u~div .email-container {\n"
                + "                min-width: 375px !important;\n"
                + "            }\n"
                + "        }\n"
                + "\n"
                + "        /* iPhone 6+, 7+, and 8+ */\n"
                + "        @media only screen and (min-device-width: 414px) {\n"
                + "            u~div .email-container {\n"
                + "                min-width: 414px !important;\n"
                + "            }\n"
                + "        }\n"
                + "    </style>\n"
                + "\n"
                + "    <!-- CSS Reset : END -->\n"
                + "\n"
                + "    <!-- Progressive Enhancements : BEGIN -->\n"
                + "    <style>\n"
                + "        .primary {\n"
                + "            background: #17bebb;\n"
                + "        }\n"
                + "\n"
                + "        .bg_white {\n"
                + "            background: #ffffff;\n"
                + "        }\n"
                + "\n"
                + "        .bg_light {\n"
                + "            background: #f7fafa;\n"
                + "        }\n"
                + "\n"
                + "        .bg_black {\n"
                + "            background: #000000;\n"
                + "        }\n"
                + "\n"
                + "        .bg_dark {\n"
                + "            background: rgba(0, 0, 0, .8);\n"
                + "        }\n"
                + "\n"
                + "        .email-section {\n"
                + "            padding: 0 2.5em;\n"
                + "        }\n"
                + "\n"
                + "        /*BUTTON*/\n"
                + "        .btn {\n"
                + "            padding: 10px 15px;\n"
                + "            display: inline-block;\n"
                + "        }\n"
                + "\n"
                + "        .btn.btn-primary {\n"
                + "            border-radius: 5px;\n"
                + "            background: #17bebb;\n"
                + "            color: #ffffff;\n"
                + "        }\n"
                + "\n"
                + "        .btn.btn-white {\n"
                + "            border-radius: 5px;\n"
                + "            background: #ffffff;\n"
                + "            color: #000000;\n"
                + "        }\n"
                + "\n"
                + "        .btn.btn-white-outline {\n"
                + "            border-radius: 5px;\n"
                + "            background: transparent;\n"
                + "            border: 1px solid #fff;\n"
                + "            color: #fff;\n"
                + "        }\n"
                + "\n"
                + "        .btn.btn-black-outline {\n"
                + "            border-radius: 0px;\n"
                + "            background: transparent;\n"
                + "            border: 2px solid #000;\n"
                + "            color: #000;\n"
                + "            font-weight: 700;\n"
                + "        }\n"
                + "\n"
                + "        .btn-custom {\n"
                + "            color: rgba(0, 0, 0, .3);\n"
                + "            text-decoration: underline;\n"
                + "        }\n"
                + "\n"
                + "        h1,\n"
                + "        h2,\n"
                + "        h3,\n"
                + "        h4,\n"
                + "        h5,\n"
                + "        h6 {\n"
                + "            font-family: 'Poppins', sans-serif;\n"
                + "            color: #000000;\n"
                + "            margin-top: 0;\n"
                + "            font-weight: 400;\n"
                + "        }\n"
                + "\n"
                + "        body {\n"
                + "            font-family: 'Poppins', sans-serif;\n"
                + "            font-weight: 400;\n"
                + "            font-size: 15px;\n"
                + "            line-height: 1.8;\n"
                + "            color: rgba(0, 0, 0, .4);\n"
                + "        }\n"
                + "\n"
                + "        a {\n"
                + "            color: #17bebb;\n"
                + "        }\n"
                + "\n"
                + "        table {}\n"
                + "\n"
                + "        /*LOGO*/\n"
                + "\n"
                + "        .logo h1 {\n"
                + "            margin: 0;\n"
                + "        }\n"
                + "\n"
                + "        .logo h1 a {\n"
                + "            color: #17bebb;\n"
                + "            font-size: 24px;\n"
                + "            font-weight: 700;\n"
                + "            font-family: 'Poppins', sans-serif;\n"
                + "        }\n"
                + "\n"
                + "        /*HERO*/\n"
                + "        .hero {\n"
                + "            position: relative;\n"
                + "            z-index: 0;\n"
                + "        }\n"
                + "\n"
                + "        .hero .text {\n"
                + "            color: rgba(0, 0, 0, .3);\n"
                + "        }\n"
                + "\n"
                + "        .hero .text h2 {\n"
                + "            color: #000;\n"
                + "            font-size: 34px;\n"
                + "            margin-bottom: 0;\n"
                + "            font-weight: 200;\n"
                + "            line-height: 1.4;\n"
                + "        }\n"
                + "\n"
                + "        .hero .text h3 {\n"
                + "            font-size: 24px;\n"
                + "            font-weight: 300;\n"
                + "        }\n"
                + "\n"
                + "        .hero .text h2 span {\n"
                + "            font-weight: 600;\n"
                + "            color: #000;\n"
                + "        }\n"
                + "\n"
                + "        .text-author {\n"
                + "            bordeR: 1px solid rgba(0, 0, 0, .05);\n"
                + "            max-width: 50%;\n"
                + "            margin: 0 auto;\n"
                + "            padding: 2em;\n"
                + "        }\n"
                + "\n"
                + "        .text-author img {\n"
                + "            border-radius: 50%;\n"
                + "            padding-bottom: 20px;\n"
                + "        }\n"
                + "\n"
                + "        .text-author h3 {\n"
                + "            margin-bottom: 0;\n"
                + "        }\n"
                + "\n"
                + "        ul.social {\n"
                + "            padding: 0;\n"
                + "        }\n"
                + "\n"
                + "        ul.social li {\n"
                + "            display: inline-block;\n"
                + "            margin-right: 10px;\n"
                + "        }\n"
                + "\n"
                + "        /*FOOTER*/\n"
                + "\n"
                + "        .footer {\n"
                + "            border-top: 1px solid rgba(0, 0, 0, .05);\n"
                + "            color: rgba(0, 0, 0, .5);\n"
                + "        }\n"
                + "\n"
                + "        .footer .heading {\n"
                + "            color: #000;\n"
                + "            font-size: 20px;\n"
                + "        }\n"
                + "\n"
                + "        .footer ul {\n"
                + "            margin: 0;\n"
                + "            padding: 0;\n"
                + "        }\n"
                + "\n"
                + "        .footer ul li {\n"
                + "            list-style: none;\n"
                + "            margin-bottom: 10px;\n"
                + "        }\n"
                + "\n"
                + "        .footer ul li a {\n"
                + "            color: rgba(0, 0, 0, 1);\n"
                + "        }\n"
                + "\n"
                + "\n"
                + "        @media screen and (max-width: 500px) {}\n"
                + "    </style>\n"
                + "\n"
                + "\n"
                + "</head>\n"
                + "\n"
                + "<body width=\"100%\" style=\"margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #f1f1f1;\">\n"
                + "    <center style=\"width: 100%; background-color: #f5cdcd;\">\n"
                + "        <div\n"
                + "            style=\"display: none; font-size: 1px;max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;\">\n"
                + "            &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;\n"
                + "        </div>\n"
                + "        <div style=\"max-width: 600px; margin: 0 auto;\" class=\"email-container\">\n"
                + "            <!-- BEGIN BODY -->\n"
                + "            <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\"\n"
                + "                style=\"margin: auto;\">\n"
                + "                <tr>\n"
                + "                    <td valign=\"top\" class=\"bg_white\" style=\"padding: 1em 2.5em 0 2.5em;\">\n"
                + "                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
                + "                            <tr>\n"
                + "                                <td class=\"logo\" style=\"text-align: center;\">\n"
                + "                                    <h1><a href=\"#\">Kích hoạt tài khoản của bạn</a></h1>\n"
                + "                                </td>\n"
                + "                            </tr>\n"
                + "                        </table>\n"
                + "                    </td>\n"
                + "                </tr><!-- end tr -->\n"
                + "                <tr>\n"
                + "                    <td valign=\"middle\" class=\"hero bg_white\" style=\"padding: 2em 0 4em 0;\">\n"
                + "                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
                + "                            <tr>\n"
                + "                                <td style=\"text-align: center;\">\n"
                + "                                    <div class=\"text-author\">\n"
                + "                                        <img src=\"images/person_2.jpg\" alt=\"\"\n"
                + "                                            style=\"width: 100px; max-width: 600px; height: auto; margin: auto; display: block;\">\n"
                + "                                        <span class=\"position\" style=\"color: black;\">Vui lòng kích hoạt tài khoản của bạn thông qua liên kết này</span>\n"
                + "                                        <p><a id=\"link\" href=" + link + " class=\"btn btn-primary\">Kích hoạt tài khoản</a></p>\n"
                + "                                    </div>\n"
                + "                                </td>\n"
                + "                            </tr>\n"
                + "                        </table>\n"
                + "                    </td>\n"
                + "                </tr><!-- end tr -->\n"
                + "                <!-- 1 Column Text + Button : END -->\n"
                + "            </table>\n"
                + "            <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\"\n"
                + "                style=\"margin: auto;\">\n"
                + "                <tr>\n"
                + "                    <td valign=\"middle\" class=\"bg_light footer email-section\">\n"
                + "                        <table>\n"
                + "                            <tr>\n"
                + "                                <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 10px;\">\n"
                + "                                    <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\n"
                + "                                        <tr>\n"
                + "                                            <td style=\"text-align: left; padding-left: 5px; padding-right: 5px;\">\n"
                + "                                                <h3 class=\"heading\" style=\"text-align: center; color: indigo; margin-bottom: 15px;\">Liên hệ chúng tôi</h3>\n"
                + "                                                <ul>\n"
                + "                                                    <li><span class=\"text\" style=\"color: black;\"><strong style=\"color: #17bebb; margin-right: 5px;\">Địa chỉ: </strong>Đại học FPT, Thạch Hoà, Thạch Thất, Hà Nội</span></li>\n"
                + "                                                    <li><span class=\"text\" style=\"color: black;\"><strong style=\"color: #17bebb; margin-right: 5px;\">SĐT: </strong>0979999999</span></a></li>\n"
                + "                                                </ul>\n"
                + "                                            </td>\n"
                + "                                        </tr>\n"
                + "                                    </table>\n"
                + "                                </td>\n"
                + "                            </tr>\n"
                + "                        </table>\n"
                + "                    </td>\n"
                + "                </tr><!-- end: tr -->\n"
                + "                <tr>\n"
                + "                    <td class=\"bg_light\" style=\"text-align: center;\">\n"
                + "                        <p style=\"color: crimson; margin-bottom: 10px; margin-top: 0;\">Đây là email tự động, vui lòng không phản hồi email này.</p>\n"
                + "                    </td>\n"
                + "                </tr>\n"
                + "            </table>\n"
                + "\n"
                + "        </div>\n"
                + "    </center>\n"
                + "</body>\n"
                + "\n"
                + "</html>";
        sendMail("Kích hoạt tài khoản của bạn", emailTo, content);
    }

    public static void sendMailToForgotPassword(String emailTo, String user_token) {
        String link = "\"" + "http://localhost:9999/ManageLodgingHouse/view/login/forgot-password.jsp?user_token=" + user_token + "\"";
        String content = "<!DOCTYPE html>\n"
                + "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\"\n"
                + "    xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
                + "\n"
                + "<head>\n"
                + "    <meta charset=\"utf-8\"> <!-- utf-8 works for most cases -->\n"
                + "    <meta name=\"viewport\" content=\"width=device-width\"> <!-- Forcing initial-scale shouldn't be necessary -->\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> <!-- Use the latest (edge) version of IE rendering engine -->\n"
                + "    <meta name=\"x-apple-disable-message-reformatting\"> <!-- Disable auto-scale in iOS 10 Mail entirely -->\n"
                + "    <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->\n"
                + "\n"
                + "    <link href=\"https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700\" rel=\"stylesheet\">\n"
                + "\n"
                + "    <!-- CSS Reset : BEGIN -->\n"
                + "    <style>\n"
                + "        /* What it does: Remove spaces around the email design added by some email clients. */\n"
                + "        /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */\n"
                + "        html,\n"
                + "        body {\n"
                + "            margin: 0 auto !important;\n"
                + "            padding: 0 !important;\n"
                + "            height: 100% !important;\n"
                + "            width: 100% !important;\n"
                + "            background: #f1f1f1;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Stops email clients resizing small text. */\n"
                + "        * {\n"
                + "            -ms-text-size-adjust: 100%;\n"
                + "            -webkit-text-size-adjust: 100%;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Centers email on Android 4.4 */\n"
                + "        div[style*=\"margin: 16px 0\"] {\n"
                + "            margin: 0 !important;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Stops Outlook from adding extra spacing to tables. */\n"
                + "        table,\n"
                + "        td {\n"
                + "            mso-table-lspace: 0pt !important;\n"
                + "            mso-table-rspace: 0pt !important;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Fixes webkit padding issue. */\n"
                + "        table {\n"
                + "            border-spacing: 0 !important;\n"
                + "            border-collapse: collapse !important;\n"
                + "            table-layout: fixed !important;\n"
                + "            margin: 0 auto !important;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Uses a better rendering method when resizing images in IE. */\n"
                + "        img {\n"
                + "            -ms-interpolation-mode: bicubic;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Prevents Windows 10 Mail from underlining links despite inline CSS. Styles for underlined links should be inline. */\n"
                + "        a {\n"
                + "            text-decoration: none;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: A work-around for email clients meddling in triggered links. */\n"
                + "        *[x-apple-data-detectors],\n"
                + "        /* iOS */\n"
                + "        .unstyle-auto-detected-links *,\n"
                + "        .aBn {\n"
                + "            border-bottom: 0 !important;\n"
                + "            cursor: default !important;\n"
                + "            color: inherit !important;\n"
                + "            text-decoration: none !important;\n"
                + "            font-size: inherit !important;\n"
                + "            font-family: inherit !important;\n"
                + "            font-weight: inherit !important;\n"
                + "            line-height: inherit !important;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Prevents Gmail from displaying a download button on large, non-linked images. */\n"
                + "        .a6S {\n"
                + "            display: none !important;\n"
                + "            opacity: 0.01 !important;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Prevents Gmail from changing the text color in conversation threads. */\n"
                + "        .im {\n"
                + "            color: inherit !important;\n"
                + "        }\n"
                + "\n"
                + "        /* If the above doesn't work, add a .g-img class to any image in question. */\n"
                + "        img.g-img+div {\n"
                + "            display: none !important;\n"
                + "        }\n"
                + "\n"
                + "        /* What it does: Removes right gutter in Gmail iOS app: https://github.com/TedGoas/Cerberus/issues/89  */\n"
                + "        /* Create one of these media queries for each additional viewport size you'd like to fix */\n"
                + "\n"
                + "        /* iPhone 4, 4S, 5, 5S, 5C, and 5SE */\n"
                + "        @media only screen and (min-device-width: 320px) and (max-device-width: 374px) {\n"
                + "            u~div .email-container {\n"
                + "                min-width: 320px !important;\n"
                + "            }\n"
                + "        }\n"
                + "\n"
                + "        /* iPhone 6, 6S, 7, 8, and X */\n"
                + "        @media only screen and (min-device-width: 375px) and (max-device-width: 413px) {\n"
                + "            u~div .email-container {\n"
                + "                min-width: 375px !important;\n"
                + "            }\n"
                + "        }\n"
                + "\n"
                + "        /* iPhone 6+, 7+, and 8+ */\n"
                + "        @media only screen and (min-device-width: 414px) {\n"
                + "            u~div .email-container {\n"
                + "                min-width: 414px !important;\n"
                + "            }\n"
                + "        }\n"
                + "    </style>\n"
                + "\n"
                + "    <!-- CSS Reset : END -->\n"
                + "\n"
                + "    <!-- Progressive Enhancements : BEGIN -->\n"
                + "    <style>\n"
                + "        .primary {\n"
                + "            background: #17bebb;\n"
                + "        }\n"
                + "\n"
                + "        .bg_white {\n"
                + "            background: #ffffff;\n"
                + "        }\n"
                + "\n"
                + "        .bg_light {\n"
                + "            background: #f7fafa;\n"
                + "        }\n"
                + "\n"
                + "        .bg_black {\n"
                + "            background: #000000;\n"
                + "        }\n"
                + "\n"
                + "        .bg_dark {\n"
                + "            background: rgba(0, 0, 0, .8);\n"
                + "        }\n"
                + "\n"
                + "        .email-section {\n"
                + "            padding: 0 2.5em;\n"
                + "        }\n"
                + "\n"
                + "        /*BUTTON*/\n"
                + "        .btn {\n"
                + "            padding: 10px 15px;\n"
                + "            display: inline-block;\n"
                + "        }\n"
                + "\n"
                + "        .btn.btn-primary {\n"
                + "            border-radius: 5px;\n"
                + "            background: #17bebb;\n"
                + "            color: #ffffff;\n"
                + "        }\n"
                + "\n"
                + "        .btn.btn-white {\n"
                + "            border-radius: 5px;\n"
                + "            background: #ffffff;\n"
                + "            color: #000000;\n"
                + "        }\n"
                + "\n"
                + "        .btn.btn-white-outline {\n"
                + "            border-radius: 5px;\n"
                + "            background: transparent;\n"
                + "            border: 1px solid #fff;\n"
                + "            color: #fff;\n"
                + "        }\n"
                + "\n"
                + "        .btn.btn-black-outline {\n"
                + "            border-radius: 0px;\n"
                + "            background: transparent;\n"
                + "            border: 2px solid #000;\n"
                + "            color: #000;\n"
                + "            font-weight: 700;\n"
                + "        }\n"
                + "\n"
                + "        .btn-custom {\n"
                + "            color: rgba(0, 0, 0, .3);\n"
                + "            text-decoration: underline;\n"
                + "        }\n"
                + "\n"
                + "        h1,\n"
                + "        h2,\n"
                + "        h3,\n"
                + "        h4,\n"
                + "        h5,\n"
                + "        h6 {\n"
                + "            font-family: 'Poppins', sans-serif;\n"
                + "            color: #000000;\n"
                + "            margin-top: 0;\n"
                + "            font-weight: 400;\n"
                + "        }\n"
                + "\n"
                + "        body {\n"
                + "            font-family: 'Poppins', sans-serif;\n"
                + "            font-weight: 400;\n"
                + "            font-size: 15px;\n"
                + "            line-height: 1.8;\n"
                + "            color: rgba(0, 0, 0, .4);\n"
                + "        }\n"
                + "\n"
                + "        a {\n"
                + "            color: #17bebb;\n"
                + "        }\n"
                + "\n"
                + "        table {}\n"
                + "\n"
                + "        /*LOGO*/\n"
                + "\n"
                + "        .logo h1 {\n"
                + "            margin: 0;\n"
                + "        }\n"
                + "\n"
                + "        .logo h1 a {\n"
                + "            color: #17bebb;\n"
                + "            font-size: 24px;\n"
                + "            font-weight: 700;\n"
                + "            font-family: 'Poppins', sans-serif;\n"
                + "        }\n"
                + "\n"
                + "        /*HERO*/\n"
                + "        .hero {\n"
                + "            position: relative;\n"
                + "            z-index: 0;\n"
                + "        }\n"
                + "\n"
                + "        .hero .text {\n"
                + "            color: rgba(0, 0, 0, .3);\n"
                + "        }\n"
                + "\n"
                + "        .hero .text h2 {\n"
                + "            color: #000;\n"
                + "            font-size: 34px;\n"
                + "            margin-bottom: 0;\n"
                + "            font-weight: 200;\n"
                + "            line-height: 1.4;\n"
                + "        }\n"
                + "\n"
                + "        .hero .text h3 {\n"
                + "            font-size: 24px;\n"
                + "            font-weight: 300;\n"
                + "        }\n"
                + "\n"
                + "        .hero .text h2 span {\n"
                + "            font-weight: 600;\n"
                + "            color: #000;\n"
                + "        }\n"
                + "\n"
                + "        .text-author {\n"
                + "            bordeR: 1px solid rgba(0, 0, 0, .05);\n"
                + "            max-width: 50%;\n"
                + "            margin: 0 auto;\n"
                + "            padding: 2em;\n"
                + "        }\n"
                + "\n"
                + "        .text-author img {\n"
                + "            border-radius: 50%;\n"
                + "            padding-bottom: 20px;\n"
                + "        }\n"
                + "\n"
                + "        .text-author h3 {\n"
                + "            margin-bottom: 0;\n"
                + "        }\n"
                + "\n"
                + "        ul.social {\n"
                + "            padding: 0;\n"
                + "        }\n"
                + "\n"
                + "        ul.social li {\n"
                + "            display: inline-block;\n"
                + "            margin-right: 10px;\n"
                + "        }\n"
                + "\n"
                + "        /*FOOTER*/\n"
                + "\n"
                + "        .footer {\n"
                + "            border-top: 1px solid rgba(0, 0, 0, .05);\n"
                + "            color: rgba(0, 0, 0, .5);\n"
                + "        }\n"
                + "\n"
                + "        .footer .heading {\n"
                + "            color: #000;\n"
                + "            font-size: 20px;\n"
                + "        }\n"
                + "\n"
                + "        .footer ul {\n"
                + "            margin: 0;\n"
                + "            padding: 0;\n"
                + "        }\n"
                + "\n"
                + "        .footer ul li {\n"
                + "            list-style: none;\n"
                + "            margin-bottom: 10px;\n"
                + "        }\n"
                + "\n"
                + "        .footer ul li a {\n"
                + "            color: rgba(0, 0, 0, 1);\n"
                + "        }\n"
                + "\n"
                + "\n"
                + "        @media screen and (max-width: 500px) {}\n"
                + "    </style>\n"
                + "\n"
                + "\n"
                + "</head>\n"
                + "\n"
                + "<body width=\"100%\" style=\"margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #f1f1f1;\">\n"
                + "    <center style=\"width: 100%; background-color: #f5cdcd;\">\n"
                + "        <div\n"
                + "            style=\"display: none; font-size: 1px;max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;\">\n"
                + "            &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;\n"
                + "        </div>\n"
                + "        <div style=\"max-width: 600px; margin: 0 auto;\" class=\"email-container\">\n"
                + "            <!-- BEGIN BODY -->\n"
                + "            <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\"\n"
                + "                style=\"margin: auto;\">\n"
                + "                <tr>\n"
                + "                    <td valign=\"top\" class=\"bg_white\" style=\"padding: 1em 2.5em 0 2.5em;\">\n"
                + "                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
                + "                            <tr>\n"
                + "                                <td class=\"logo\" style=\"text-align: center;\">\n"
                + "                                    <h1><a href=\"#\">Quên mật khẩu</a></h1>\n"
                + "                                </td>\n"
                + "                            </tr>\n"
                + "                        </table>\n"
                + "                    </td>\n"
                + "                </tr><!-- end tr -->\n"
                + "                <tr>\n"
                + "                    <td valign=\"middle\" class=\"hero bg_white\" style=\"padding: 2em 0 4em 0;\">\n"
                + "                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
                + "                            <tr>\n"
                + "                                <td style=\"text-align: center;\">\n"
                + "                                    <div class=\"text-author\">\n"
                + "                                        <img src=\"images/person_2.jpg\" alt=\"\"\n"
                + "                                            style=\"width: 100px; max-width: 600px; height: auto; margin: auto; display: block;\">\n"
                + "                                        <span class=\"position\" style=\"color: black;\">Để lấy lại mật khẩu, bấm vào đường link sau</span>\n"
                + "                                        <p><a id=\"link\" href=" + link + " class=\"btn btn-primary\">Lấy lại mật khẩu</a></p>\n"
                + "                                    </div>\n"
                + "                                </td>\n"
                + "                            </tr>\n"
                + "                        </table>\n"
                + "                    </td>\n"
                + "                </tr><!-- end tr -->\n"
                + "                <!-- 1 Column Text + Button : END -->\n"
                + "            </table>\n"
                + "            <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\"\n"
                + "                style=\"margin: auto;\">\n"
                + "                <tr>\n"
                + "                    <td valign=\"middle\" class=\"bg_light footer email-section\">\n"
                + "                        <table>\n"
                + "                            <tr>\n"
                + "                                <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 10px;\">\n"
                + "                                    <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\n"
                + "                                        <tr>\n"
                + "                                            <td style=\"text-align: left; padding-left: 5px; padding-right: 5px;\">\n"
                + "                                                <h3 class=\"heading\" style=\"text-align: center; color: indigo; margin-bottom: 15px;\">Liên hệ chúng tôi</h3>\n"
                + "                                                <ul>\n"
                + "                                                    <li><span class=\"text\" style=\"color: black;\"><strong style=\"color: #17bebb; margin-right: 5px;\">Địa chỉ: </strong>Đại học FPT, Thạch Hoà, Thạch Thất, Hà Nội</span></li>\n"
                + "                                                    <li><span class=\"text\" style=\"color: black;\"><strong style=\"color: #17bebb; margin-right: 5px;\">SĐT: </strong>0979999999</span></a></li>\n"
                + "                                                </ul>\n"
                + "                                            </td>\n"
                + "                                        </tr>\n"
                + "                                    </table>\n"
                + "                                </td>\n"
                + "                            </tr>\n"
                + "                        </table>\n"
                + "                    </td>\n"
                + "                </tr><!-- end: tr -->\n"
                + "                <tr>\n"
                + "                    <td class=\"bg_light\" style=\"text-align: center;\">\n"
                + "                        <p style=\"color: crimson; margin-bottom: 10px; margin-top: 0;\">Đây là email tự động, vui lòng không phản hồi email này.</p>\n"
                + "                    </td>\n"
                + "                </tr>\n"
                + "            </table>\n"
                + "\n"
                + "        </div>\n"
                + "    </center>\n"
                + "</body>\n"
                + "\n"
                + "</html>";
        sendMail("Lấy lại mật khẩu của bạn", emailTo, content);
    }

    public static void sendMailToNotifyPayment(String mailTo, String monthYear, String fullName, double totalAmount) {
        String content = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "\n"
                + "    <style>\n"
                + "        label {\n"
                + "            line-height: 50px;\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "    <div class=\"container\">\n"
                + "        <label>Chào <strong>"+fullName+"</strong>,</label><br>\n"
                + "\n"
                + "        <label>\n"
                + "            Chúc bạn một ngày tốt lành. Thông qua email này,\n"
                + "            tôi muốn nhắc nhở bạn về việc nộp tiền thuê phòng cho tháng <strong>"+monthYear+"</strong>. Vui lòng hoàn\n"
                + "            thành thanh toán sớm nhất có thể.\n"
                + "        </label><br>\n"
                + "\n"
                + "        <label>Số tiền cần nộp: <strong style=\"color: red;\">"+totalAmount+"</strong></label><br>\n"
                + "\n"
                + "        <label>\n"
                + "            Bạn có thể thanh toán online bằng cách truy cập vào hệ thống quản lý trọ để thanh toán hoặc\n"
                + "            có thể gặp trực tiếp quản lý(chủ trọ) để thanh toán tiền mặt.\n"
                + "        </label><br>\n"
                + "\n"
                + "        <label>\n"
                + "            Nếu bạn gặp bất kỳ khó khăn nào, xin hãy thông báo cho tôi để chúng ta có thể tìm cách giải quyết.\n"
                + "        </label><br>\n"
                + "\n"
                + "        <div style=\"margin-top: 30px;\">\n"
                + "            <label>Trân trọng, <strong>Quản lý nhà trọ</strong></label><br>\n"
                + "        </div>\n"
                + "        <hr>\n"
                + "        <label>\n"
                + "            Liên hệ chúng tôi qua:\n"
                + "        </label><br>\n"
                + "        <label>\n"
                + "            <strong>Địa chỉ:</strong> Đại học FPT, Thạch Hoà, Thạch Thất, Hà Nội\n"
                + "        </label><br>\n"
                + "        <label>\n"
                + "            <strong>SĐT:</strong> 0979999999\n"
                + "        </label>\n"
                + "    </div>\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        sendMail("Nhắc nhở nộp tiền thuê phòng tháng " + monthYear, mailTo, content);
    }

    public static void sendMail(String subject, String emailTo, String content) {

        try {
            Properties properties = new Properties();
            properties.put("mail.smtp.host", "smtp.gmail.com"); // SMTP HOST
            properties.put("mail.smtp.port", "587"); // TLS 587 SSL 465
            properties.put("mail.smtp.auth", "true");
            properties.put("mail.smtp.starttls.enable", "true");

            Authenticator auth = new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(FROM, PASSWORD);
                }
            };

            // tạo ra 1 phiên làm việc: đăng nhập vào gmail với Authenticator
            Session session = Session.getInstance(properties, auth);

            // gửi mail
            MimeMessage message = new MimeMessage(session);
            // kiểu dữ liệu muốn gửi
            message.addHeader("Content-type", "text/HTML; charset=UTF-8");
            // gửi từ 
            message.setFrom(FROM);
            // gủi đến và kiểu gửi
            message.setRecipients(Message.RecipientType.TO, emailTo);
            // set tiêu đề
            message.setSubject(subject, "UTF-8");
            // set nội dung           
            message.setContent(content, "text/HTML; charset=UTF-8");
            // gửi mail
            Transport.send(message);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        EmailService.sendMailToNotifyPayment("anhnhatlop8ab@gmail.com", "2024-06", "Trần Anh Nhật", 3480000);
    }
}
